### PR TITLE
Update controllers/AdminRowController.php

### PR DESCRIPTION
**Pull request by frenchcomp**
Fix bug : add "container_id" element in post action (with a new form, the action send to post action)
But, if the element does not exist, the value is not put into the row)

And use extraParam to keep the container into the request

### CODE REVIEW

**Comment by lchenay** [comment]
You should not need to add Element container_id.
If the key/value is in _extraParam, it should be pass in the url of the form's action.

Does it ?

**Comment by Floby** [comment]
Maybe if the form is created before the container_id is set in _extraParams, it get ignored. Because _getForm makes a setAction() on the form.

**Comment by Floby** [comment]
:(

**Comment by lchenay** [comment]
:(

**Pull request closed without merging**
